=== CrazyForks/jollyday/jollyday-core/src/main/resources/Holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/Holiday"
        xmlns:tns="http://www.example.org/Holiday"
        elementFormDefault="qualified">

  <simpleType name="Weekday">
    <restriction base="string">
      <enumeration value="MONDAY"/>
      <enumeration value="TUESDAY"/>
      <enumeration value="WEDNESDAY"/>
      <enumeration value="THURSDAY"/>
      <enumeration value="FRIDAY"/>
      <enumeration value="SATURDAY"/>
      <enumeration value="SUNDAY"/>
    </restriction>
  </simpleType>

  <simpleType name="Month">
    <restriction base="string">
      <enumeration value="JANUARY"/>
      <enumeration value="FEBRUARY"/>
      <enumeration value="MARCH"/>
      <enumeration value="APRIL"/>
      <enumeration value="MAY"/>
      <enumeration value="JUNE"/>
      <enumeration value="JULY"/>
      <enumeration value="AUGUST"/>
      <enumeration value="SEPTEMBER"/>
      <enumeration value="OCTOBER"/>
      <enumeration value="NOVEMBER"/>
      <enumeration value="DECEMBER"/>
    </restriction>
  </simpleType>

  <complexType name="RelativeToFixed">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <choice maxOccurs="1" minOccurs="1">
            <element name="Days" type="int" maxOccurs="1" minOccurs="0"/>
            <element name="Weekday" type="tns:Weekday" maxOccurs="1" minOccurs="0"/>
          </choice>
          <element name="When" type="tns:When"/>
          <element name="Date" type="tns:Fixed"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Holidays">
    <sequence>
      <element name="Fixed" type="tns:Fixed" maxOccurs="unbounded" minOccurs="0"/>
      <element name="RelativeToFixed" type="tns:RelativeToFixed" maxOccurs="unbounded" minOccurs="0"/>
      <element name="RelativeToWeekdayInMonth" type="tns:RelativeToWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <element name="FixedWeekday" type="tns:FixedWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <element name="ChristianHoliday" type="tns:ChristianHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <element name="IslamicHoliday" type="tns:IslamicHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <element name="FixedWeekdayBetweenFixed" type="tns:FixedWeekdayBetweenFixed" maxOccurs="unbounded" minOccurs="0"/>
      <element name="FixedWeekdayRelativeToFixed" type="tns:FixedWeekdayRelativeToFixed" maxOccurs="unbounded"
               minOccurs="0"/>
      <element name="EthiopianOrthodoxHoliday" type="tns:EthiopianOrthodoxHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <element name="RelativeToEasterSunday" type="tns:RelativeToEasterSunday" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <element name="Configuration" type="tns:Configuration"/>

  <complexType name="Configuration">
    <sequence>
      <element name="Holidays" type="tns:Holidays"/>
      <element name="SubConfigurations" type="tns:Configuration" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="hierarchy" type="string"/>
    <attribute name="description" type="string"/>
  </complexType>

  <complexType name="Fixed">
    <complexContent>
      <extension base="tns:MoveableHoliday">
        <attribute name="month" type="tns:Month"/>
        <attribute name="day">
          <simpleType>
            <restriction base="int">
              <minInclusive value="1"/>
              <maxInclusive value="31"/>
            </restriction>
          </simpleType>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="When">
    <restriction base="string">
      <enumeration value="BEFORE"/>
      <enumeration value="AFTER"/>
      <enumeration value="CLOSEST"/>
    </restriction>
  </simpleType>

  <complexType name="FixedWeekdayInMonth">
    <complexContent>
      <extension base="tns:Holiday">
        <attribute name="which" type="tns:Which"/>
        <attribute name="weekday" type="tns:Weekday"/>
        <attribute name="month" type="tns:Month"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="Which">
    <restriction base="string">
      <enumeration value="FIRST"/>
      <enumeration value="SECOND"/>
      <enumeration value="THIRD"/>
      <enumeration value="FOURTH"/>
      <enumeration value="LAST"/>
    </restriction>
  </simpleType>

  <complexType name="RelativeToWeekdayInMonth">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="FixedWeekday" type="tns:FixedWeekdayInMonth"/>
        </sequence>
        <attribute name="weekday" type="tns:Weekday"/>
        <attribute name="when" type="tns:When"/>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="IslamicHoliday">
    <complexContent>
      <extension base="tns:Holiday">
        <attribute name="type" type="tns:IslamicHolidayType"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="IslamicHolidayType">
    <restriction base="string">
      <enumeration value="NEWYEAR"/>
      <enumeration value="ASCHURA"/>
      <enumeration value="MAWLID_AN_NABI"/>
      <enumeration value="LAILAT_AL_MIRAJ"/>
      <enumeration value="LAILAT_AL_BARAT"/>
      <enumeration value="RAMADAN"/>
      <enumeration value="LAILAT_AL_QADR"/>
      <enumeration value="RAMADAN_END"/>
      <enumeration value="ID_AL_FITR"/>
      <enumeration value="ID_AL_FITR_2"/>
      <enumeration value="ID_AL_FITR_3"/>
      <enumeration value="ARAFAAT"/>
      <enumeration value="ID_UL_ADHA"/>
      <enumeration value="ID_UL_ADHA_2"/>
      <enumeration value="ID_UL_ADHA_3"/>
    </restriction>
  </simpleType>

  <simpleType name="ChronologyType">
    <restriction base="string">
      <enumeration value="JULIAN"/>
      <enumeration value="GREGORIAN"/>
    </restriction>
  </simpleType>

  <complexType name="ChristianHoliday">
    <complexContent>
      <extension base="tns:MoveableHoliday">
        <attribute name="type" type="tns:ChristianHolidayType"/>
        <attribute name="chronology" type="tns:ChronologyType"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="HolidayType">
    <restriction base="string">
      <enumeration value="OFFICIAL_HOLIDAY"/>
      <enumeration value="UNOFFICIAL_HOLIDAY"/>
    </restriction>
  </simpleType>

  <simpleType name="ChristianHolidayType">
    <restriction base="string">
      <enumeration value="GOOD_FRIDAY"/>
      <enumeration value="EASTER_MONDAY"/>
      <enumeration value="ASCENSION_DAY"/>
      <enumeration value="WHIT_MONDAY"/>
      <enumeration value="CORPUS_CHRISTI"/>
      <enumeration value="MAUNDY_THURSDAY"/>
      <enumeration value="ASH_WEDNESDAY"/>
      <enumeration value="MARDI_GRAS"/>
      <enumeration value="GENERAL_PRAYER_DAY"/>
      <enumeration value="CLEAN_MONDAY"/>
      <enumeration value="SHROVE_MONDAY"/>
      <enumeration value="PENTECOST"/>
      <enumeration value="CARNIVAL"/>
      <enumeration value="EASTER_SATURDAY"/>
      <enumeration value="EASTER_TUESDAY"/>
      <enumeration value="SACRED_HEART"/>
      <enumeration value="EASTER"/>
      <enumeration value="PENTECOST_MONDAY"/>
      <enumeration value="WHIT_SUNDAY"/>
    </restriction>
  </simpleType>

  <complexType name="FixedWeekdayBetweenFixed">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="from" type="tns:Fixed"/>
          <element name="to" type="tns:Fixed"/>
        </sequence>
        <attribute name="weekday" type="tns:Weekday"/>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Holiday" abstract="true">
    <attribute name="validFrom" type="int"/>
    <attribute name="validTo" type="int"/>
    <attribute name="every" type="tns:HolidayCycleType" default="EVERY_YEAR"/>
    <attribute name="descriptionPropertiesKey" type="string"/>
    <attribute name="localizedType" type="tns:HolidayType" default="OFFICIAL_HOLIDAY"/>
  </complexType>

  <simpleType name="Substituted">
    <restriction base="string">
      <enumeration value="ON_SATURDAY"/>
      <enumeration value="ON_SUNDAY"/>
      <enumeration value="ON_WEEKEND"/>
      <enumeration value="ON_TUESDAY"/>
      <enumeration value="ON_WEDNESDAY"/>
    </restriction>
  </simpleType>

  <simpleType name="With">
    <restriction base="string">
      <enumeration value="NEXT"/>
      <enumeration value="PREVIOUS"/>
    </restriction>
  </simpleType>

  <complexType name="MovingCondition">
    <attribute name="substitute" type="tns:Weekday"/>
    <attribute name="with" type="tns:With"/>
    <attribute name="weekday" type="tns:Weekday"/>
  </complexType>

  <complexType name="MoveableHoliday" abstract="true">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="MovingCondition" type="tns:MovingCondition" maxOccurs="unbounded" minOccurs="0"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="EthiopianOrthodoxHoliday">
    <complexContent>
      <extension base="tns:Holiday">
        <attribute name="type" type="tns:EthiopianOrthodoxHolidayType"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="EthiopianOrthodoxHolidayType">
    <restriction base="string">
      <enumeration value="TIMKAT"/>
      <enumeration value="ENKUTATASH"/>
      <enumeration value="MESKEL"/>
    </restriction>
  </simpleType>

  <complexType name="FixedWeekdayRelativeToFixed">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="day" type="tns:Fixed"/>
        </sequence>
        <attribute name="which" type="tns:Which"/>
        <attribute name="weekday" type="tns:Weekday"/>
        <attribute name="when" type="tns:When"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="HolidayCycleType">
    <restriction base="string">
      <enumeration value="EVERY_YEAR"/>
      <enumeration value="TWO_YEARS"/>
      <enumeration value="THREE_YEARS"/>
      <enumeration value="FOUR_YEARS"/>
      <enumeration value="FIVE_YEARS"/>
      <enumeration value="SIX_YEARS"/>
      <enumeration value="ODD_YEARS"/>
      <enumeration value="EVEN_YEARS"/>
    </restriction>
  </simpleType>

  <complexType name="RelativeToEasterSunday">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="chronology" type="tns:ChronologyType"/>
          <element name="days" type="int"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
</schema>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_vg_2017.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="vg" description="Virgin Islands (British)" xmlns:tns="http://www.example.org/Holiday"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
  <tns:Holidays>
    <tns:Fixed month="JANUARY" day="2" descriptionPropertiesKey="NEW_YEAR"/>
    <tns:Fixed month="MARCH" day="6" descriptionPropertiesKey="STOUTTS_BIRTHDAY"/>
    <tns:Fixed month="MARCH" day="13" descriptionPropertiesKey="COMMONWEALTH_DAY"/>
    <tns:Fixed month="APRIL" day="14" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <tns:Fixed month="APRIL" day="17" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <tns:Fixed month="JUNE" day="5" descriptionPropertiesKey="christian.WHIT_MONDAY"/>
    <tns:Fixed month="JUNE" day="17" descriptionPropertiesKey="SOVEREIGNS_BIRTHDAY"/>
    <tns:Fixed month="JUNE" day="30" descriptionPropertiesKey="TERRITORY_DAY"/>
    <tns:Fixed month="AUGUST" day="7" descriptionPropertiesKey="FESTIVAL_MONDAY"/>
    <tns:Fixed month="AUGUST" day="8" descriptionPropertiesKey="FESTIVAL_TUESDAY"/>
    <tns:Fixed month="AUGUST" day="9" descriptionPropertiesKey="FESTIVAL_WEDNESDAY"/>
    <tns:Fixed month="OCTOBER" day="20" descriptionPropertiesKey="ST_URSULA"/>
    <tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <tns:Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY"/>
  </tns:Holidays>
</tns:Configuration>

=== CrazyForks/jollyday/jollyday-core/src/main/resources/holidays/Holidays_target.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="target" description="Trans-European Automated Real-time Gross settlement Express Transfer system closing dates"
               xmlns="https://www.focus_shift.de/jollyday/xml/ns/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://www.focus_shift.de/jollyday/xml/ns/holiday https://www.focus_shift.de/jollyday/xml/ns/holiday/Holiday.xsd">
  <Holidays>
    <Fixed validFrom="2000" month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed validFrom="2000" month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed validFrom="1999" month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed validFrom="1999" month="DECEMBER" day="26" descriptionPropertiesKey="STEPHENS"/>
    <Fixed validFrom="2001" validTo="2001" month="DECEMBER" day="31" descriptionPropertiesKey="NEW_YEARS_EVE"/>
    <Fixed validFrom="1999" validTo="1999" month="DECEMBER" day="31" descriptionPropertiesKey="NEW_YEARS_EVE"/>
    <ChristianHoliday validFrom="2000" type="GOOD_FRIDAY" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <ChristianHoliday validFrom="2000" type="EASTER_MONDAY" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
  </Holidays>
</Configuration>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_je_2016.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="je" description="Jersey"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="MARCH" day="25" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="MARCH" day="28" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <Fixed month="MAY" day="2" descriptionPropertiesKey="EARLY_MAY_BANK_HOLIDAY"/>
    <Fixed month="MAY" day="9" descriptionPropertiesKey="LIBERATION"/>
    <Fixed month="MAY" day="30" descriptionPropertiesKey="SPRING_BANK_HOLIDAY"/>
    <Fixed month="AUGUST" day="29" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY"/>
    <Fixed month="DECEMBER" day="27" descriptionPropertiesKey="CHRISTMAS"/>
  </Holidays>
</Configuration>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_ky_2021.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="ky" description="Cayman Islands" xmlns:tns="http://www.example.org/Holiday"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
  <tns:Holidays>
    <tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <tns:Fixed month="JANUARY" day="25" descriptionPropertiesKey="NATIONAL_HEROES_DAY"/>
    <tns:Fixed month="FEBRUARY" day="17" descriptionPropertiesKey="christian.ASH_WEDNESDAY"/>
    <tns:Fixed month="APRIL" day="2" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <tns:Fixed month="APRIL" day="5" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <tns:Fixed month="APRIL" day="14" descriptionPropertiesKey="ELECTION_DAY"/>
    <tns:Fixed month="MAY" day="17" descriptionPropertiesKey="DISCOVERY_DAY"/>
    <tns:Fixed month="JUNE" day="14" descriptionPropertiesKey="QUEENS_BIRTHDAY"/>
    <tns:Fixed month="JULY" day="5" descriptionPropertiesKey="CONSTITUTION_DAY"/>
    <tns:Fixed month="NOVEMBER" day="15" descriptionPropertiesKey="REMEMBRANCE"/>
    <tns:Fixed month="DECEMBER" day="27" descriptionPropertiesKey="CHRISTMAS"/>
    <tns:Fixed month="DECEMBER" day="28" descriptionPropertiesKey="BOXING_DAY"/>
  </tns:Holidays>
</tns:Configuration>

=== CrazyForks/jollyday/jollyday-core/src/main/resources/holidays/Holidays_rs.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="rs" description="Serbia"
                   xmlns:tns="http://www.example.org/Holiday" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
  <tns:Holidays>
    <tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <tns:Fixed month="JANUARY" day="2" descriptionPropertiesKey="NEW_YEAR"/>
    <tns:Fixed month="JANUARY" day="7" descriptionPropertiesKey="CHRISTMAS"/>
    <tns:Fixed month="FEBRUARY" day="15" descriptionPropertiesKey="CONSTITUTION_DAY"/>
    <tns:Fixed month="FEBRUARY" day="16" descriptionPropertiesKey="CONSTITUTION_DAY"/>
    <tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <tns:Fixed month="MAY" day="2" descriptionPropertiesKey="LABOUR_DAY"/>
    <tns:Fixed month="MAY" day="9" descriptionPropertiesKey="VICTORY" localizedType="UNOFFICIAL_HOLIDAY"/>
    <tns:ChristianHoliday type="EASTER" descriptionPropertiesKey="christian.EASTER"/>
    <tns:ChristianHoliday type="GOOD_FRIDAY" chronology="JULIAN" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <tns:ChristianHoliday type="EASTER_MONDAY" chronology="JULIAN" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
  </tns:Holidays>
</tns:Configuration>

=== CrazyForks/jollyday/jollyday-core/src/main/resources/holidays/Holidays_cu.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="cu" description="Cuba"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="TRIUMPH_OF_THE_REVOLUTION"/>
    <Fixed month="JANUARY" day="2" descriptionPropertiesKey="VICTORY_OF_FIDEL_CASTRO"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="JULY" day="25" descriptionPropertiesKey="DAY_BEFORE_THE_COMMEMORATION_OF_THE_ASSAULT_OF_THE_MONCADA_GARRISON"/>
    <Fixed month="JULY" day="26" descriptionPropertiesKey="COMMEMORATION_OF_THE_ASSAULT_OF_THE_MONCADA_GARRISON"/>
    <Fixed month="JULY" day="27" descriptionPropertiesKey="DAY_AFTER_THE_COMMEMORATION_OF_THE_ASSAULT_OF_THE_MONCADA_GARRISON"/>
    <Fixed month="OCTOBER" day="10" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <ChristianHoliday type="GOOD_FRIDAY" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
  </Holidays>

  <Sources>
    <Source>https://en.wikipedia.org/wiki/Public_holidays_in_Cuba</Source>
    <Source of="ISO 3166">https://www.iso.org/obp/ui/#iso:code:3166:CU</Source>
    <Source of="ISO 3166-2">https://en.wikipedia.org/wiki/ISO_3166-2:CU</Source>
  </Sources>

  <SubConfigurations hierarchy="01" description="Pinar del Rio">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="03" description="Havana">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="04" description="Matanzas">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="05" description="Clara City">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="06" description="Cienfuegos">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="07" description="Holy Spirit">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="08" description="Ciego de Avila">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="09" description="Camaguey">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="10" description="Las Tunas">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="11" description="Holguin">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="12" description="Granma">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="13" description="Santiago">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="14" description="Guantanamo">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="15" description="Artemisa">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="16" description="Mayabeque">
    <Holidays/>
  </SubConfigurations>
  <SubConfigurations hierarchy="99" description="Isle of Youth">
    <Holidays/>
  </SubConfigurations>
</Configuration>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_bm_2018.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="bm" description="Bermuda" xmlns:tns="http://www.example.org/Holiday"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
  <tns:Holidays>
    <tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <tns:Fixed month="MARCH" day="30" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <tns:Fixed month="MAY" day="25" descriptionPropertiesKey="BERMUDA_DAY"/>
    <tns:Fixed month="JUNE" day="18" descriptionPropertiesKey="NATIONAL_HEROES_DAY"/>
    <tns:Fixed month="AUGUST" day="2" descriptionPropertiesKey="EMANCIPATION_DAY"/>
    <tns:Fixed month="AUGUST" day="3" descriptionPropertiesKey="SOMERS_DAY"/>
    <tns:Fixed month="SEPTEMBER" day="3" descriptionPropertiesKey="LABOUR_DAY"/>
    <tns:Fixed month="NOVEMBER" day="12" descriptionPropertiesKey="REMEMBRANCE"/>
    <tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <tns:Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY"/>
  </tns:Holidays>
</tns:Configuration>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_ky_2012.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="ky" description="Cayman Islands"
               xmlns="https://www.focus_shift.de/jollyday/xml/ns/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://www.focus_shift.de/jollyday/xml/ns/holiday https://www.focus_shift.de/jollyday/xml/ns/holiday/Holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="2" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="23" descriptionPropertiesKey="NATIONAL_HEROES_DAY"/>
    <Fixed month="FEBRUARY" day="22" descriptionPropertiesKey="christian.ASH_WEDNESDAY"/>
    <Fixed month="APRIL" day="6" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="APRIL" day="9" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <Fixed month="MAY" day="21" descriptionPropertiesKey="DISCOVERY_DAY"/>
    <Fixed month="JUNE" day="18" descriptionPropertiesKey="QUEENS_BIRTHDAY"/>
    <Fixed month="JULY" day="2" descriptionPropertiesKey="CONSTITUTION_DAY"/>
    <Fixed month="NOVEMBER" day="12" descriptionPropertiesKey="REMEMBRANCE"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY"/>
  </Holidays>
</Configuration>
