=== CrazyForks/jollyday/jollyday-core/src/main/resources/Holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/Holiday"
        xmlns:tns="http://www.example.org/Holiday"
        elementFormDefault="qualified">

  <simpleType name="Weekday">
    <restriction base="string">
      <enumeration value="MONDAY"/>
      <enumeration value="TUESDAY"/>
      <enumeration value="WEDNESDAY"/>
      <enumeration value="THURSDAY"/>
      <enumeration value="FRIDAY"/>
      <enumeration value="SATURDAY"/>
      <enumeration value="SUNDAY"/>
    </restriction>
  </simpleType>

  <simpleType name="Month">
    <restriction base="string">
      <enumeration value="JANUARY"/>
      <enumeration value="FEBRUARY"/>
      <enumeration value="MARCH"/>
      <enumeration value="APRIL"/>
      <enumeration value="MAY"/>
      <enumeration value="JUNE"/>
      <enumeration value="JULY"/>
      <enumeration value="AUGUST"/>
      <enumeration value="SEPTEMBER"/>
      <enumeration value="OCTOBER"/>
      <enumeration value="NOVEMBER"/>
      <enumeration value="DECEMBER"/>
    </restriction>
  </simpleType>

  <complexType name="RelativeToFixed">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <choice maxOccurs="1" minOccurs="1">
            <element name="Days" type="int" maxOccurs="1" minOccurs="0"/>
            <element name="Weekday" type="tns:Weekday" maxOccurs="1" minOccurs="0"/>
          </choice>
          <element name="When" type="tns:When"/>
          <element name="Date" type="tns:Fixed"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Holidays">
    <sequence>
      <element name="Fixed" type="tns:Fixed" maxOccurs="unbounded" minOccurs="0"/>
      <element name="RelativeToFixed" type="tns:RelativeToFixed" maxOccurs="unbounded" minOccurs="0"/>
      <element name="RelativeToWeekdayInMonth" type="tns:RelativeToWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <element name="FixedWeekday" type="tns:FixedWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <element name="ChristianHoliday" type="tns:ChristianHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <element name="IslamicHoliday" type="tns:IslamicHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <element name="FixedWeekdayBetweenFixed" type="tns:FixedWeekdayBetweenFixed" maxOccurs="unbounded" minOccurs="0"/>
      <element name="FixedWeekdayRelativeToFixed" type="tns:FixedWeekdayRelativeToFixed" maxOccurs="unbounded"
               minOccurs="0"/>
      <element name="EthiopianOrthodoxHoliday" type="tns:EthiopianOrthodoxHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <element name="RelativeToEasterSunday" type="tns:RelativeToEasterSunday" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <element name="Configuration" type="tns:Configuration"/>

  <complexType name="Configuration">
    <sequence>
      <element name="Holidays" type="tns:Holidays"/>
      <element name="SubConfigurations" type="tns:Configuration" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="hierarchy" type="string"/>
    <attribute name="description" type="string"/>
  </complexType>

  <complexType name="Fixed">
    <complexContent>
      <extension base="tns:MoveableHoliday">
        <attribute name="month" type="tns:Month"/>
        <attribute name="day">
          <simpleType>
            <restriction base="int">
              <minInclusive value="1"/>
              <maxInclusive value="31"/>
            </restriction>
          </simpleType>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="When">
    <restriction base="string">
      <enumeration value="BEFORE"/>
      <enumeration value="AFTER"/>
      <enumeration value="CLOSEST"/>
    </restriction>
  </simpleType>

  <complexType name="FixedWeekdayInMonth">
    <complexContent>
      <extension base="tns:Holiday">
        <attribute name="which" type="tns:Which"/>
        <attribute name="weekday" type="tns:Weekday"/>
        <attribute name="month" type="tns:Month"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="Which">
    <restriction base="string">
      <enumeration value="FIRST"/>
      <enumeration value="SECOND"/>
      <enumeration value="THIRD"/>
      <enumeration value="FOURTH"/>
      <enumeration value="LAST"/>
    </restriction>
  </simpleType>

  <complexType name="RelativeToWeekdayInMonth">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="FixedWeekday" type="tns:FixedWeekdayInMonth"/>
        </sequence>
        <attribute name="weekday" type="tns:Weekday"/>
        <attribute name="when" type="tns:When"/>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="IslamicHoliday">
    <complexContent>
      <extension base="tns:Holiday">
        <attribute name="type" type="tns:IslamicHolidayType"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="IslamicHolidayType">
    <restriction base="string">
      <enumeration value="NEWYEAR"/>
      <enumeration value="ASCHURA"/>
      <enumeration value="MAWLID_AN_NABI"/>
      <enumeration value="LAILAT_AL_MIRAJ"/>
      <enumeration value="LAILAT_AL_BARAT"/>
      <enumeration value="RAMADAN"/>
      <enumeration value="LAILAT_AL_QADR"/>
      <enumeration value="RAMADAN_END"/>
      <enumeration value="ID_AL_FITR"/>
      <enumeration value="ID_AL_FITR_2"/>
      <enumeration value="ID_AL_FITR_3"/>
      <enumeration value="ARAFAAT"/>
      <enumeration value="ID_UL_ADHA"/>
      <enumeration value="ID_UL_ADHA_2"/>
      <enumeration value="ID_UL_ADHA_3"/>
    </restriction>
  </simpleType>

  <simpleType name="ChronologyType">
    <restriction base="string">
      <enumeration value="JULIAN"/>
      <enumeration value="GREGORIAN"/>
    </restriction>
  </simpleType>

  <complexType name="ChristianHoliday">
    <complexContent>
      <extension base="tns:MoveableHoliday">
        <attribute name="type" type="tns:ChristianHolidayType"/>
        <attribute name="chronology" type="tns:ChronologyType"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="HolidayType">
    <restriction base="string">
      <enumeration value="OFFICIAL_HOLIDAY"/>
      <enumeration value="UNOFFICIAL_HOLIDAY"/>
    </restriction>
  </simpleType>

  <simpleType name="ChristianHolidayType">
    <restriction base="string">
      <enumeration value="GOOD_FRIDAY"/>
      <enumeration value="EASTER_MONDAY"/>
      <enumeration value="ASCENSION_DAY"/>
      <enumeration value="WHIT_MONDAY"/>
      <enumeration value="CORPUS_CHRISTI"/>
      <enumeration value="MAUNDY_THURSDAY"/>
      <enumeration value="ASH_WEDNESDAY"/>
      <enumeration value="MARDI_GRAS"/>
      <enumeration value="GENERAL_PRAYER_DAY"/>
      <enumeration value="CLEAN_MONDAY"/>
      <enumeration value="SHROVE_MONDAY"/>
      <enumeration value="PENTECOST"/>
      <enumeration value="CARNIVAL"/>
      <enumeration value="EASTER_SATURDAY"/>
      <enumeration value="EASTER_TUESDAY"/>
      <enumeration value="SACRED_HEART"/>
      <enumeration value="EASTER"/>
      <enumeration value="PENTECOST_MONDAY"/>
      <enumeration value="WHIT_SUNDAY"/>
    </restriction>
  </simpleType>

  <complexType name="FixedWeekdayBetweenFixed">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="from" type="tns:Fixed"/>
          <element name="to" type="tns:Fixed"/>
        </sequence>
        <attribute name="weekday" type="tns:Weekday"/>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Holiday" abstract="true">
    <attribute name="validFrom" type="int"/>
    <attribute name="validTo" type="int"/>
    <attribute name="every" type="tns:HolidayCycleType" default="EVERY_YEAR"/>
    <attribute name="descriptionPropertiesKey" type="string"/>
    <attribute name="localizedType" type="tns:HolidayType" default="OFFICIAL_HOLIDAY"/>
  </complexType>

  <simpleType name="Substituted">
    <restriction base="string">
      <enumeration value="ON_SATURDAY"/>
      <enumeration value="ON_SUNDAY"/>
      <enumeration value="ON_WEEKEND"/>
      <enumeration value="ON_TUESDAY"/>
      <enumeration value="ON_WEDNESDAY"/>
    </restriction>
  </simpleType>

  <simpleType name="With">
    <restriction base="string">
      <enumeration value="NEXT"/>
      <enumeration value="PREVIOUS"/>
    </restriction>
  </simpleType>

  <complexType name="MovingCondition">
    <attribute name="substitute" type="tns:Weekday"/>
    <attribute name="with" type="tns:With"/>
    <attribute name="weekday" type="tns:Weekday"/>
  </complexType>

  <complexType name="MoveableHoliday" abstract="true">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="MovingCondition" type="tns:MovingCondition" maxOccurs="unbounded" minOccurs="0"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="EthiopianOrthodoxHoliday">
    <complexContent>
      <extension base="tns:Holiday">
        <attribute name="type" type="tns:EthiopianOrthodoxHolidayType"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="EthiopianOrthodoxHolidayType">
    <restriction base="string">
      <enumeration value="TIMKAT"/>
      <enumeration value="ENKUTATASH"/>
      <enumeration value="MESKEL"/>
    </restriction>
  </simpleType>

  <complexType name="FixedWeekdayRelativeToFixed">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="day" type="tns:Fixed"/>
        </sequence>
        <attribute name="which" type="tns:Which"/>
        <attribute name="weekday" type="tns:Weekday"/>
        <attribute name="when" type="tns:When"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="HolidayCycleType">
    <restriction base="string">
      <enumeration value="EVERY_YEAR"/>
      <enumeration value="TWO_YEARS"/>
      <enumeration value="THREE_YEARS"/>
      <enumeration value="FOUR_YEARS"/>
      <enumeration value="FIVE_YEARS"/>
      <enumeration value="SIX_YEARS"/>
      <enumeration value="ODD_YEARS"/>
      <enumeration value="EVEN_YEARS"/>
    </restriction>
  </simpleType>

  <complexType name="RelativeToEasterSunday">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="chronology" type="tns:ChronologyType"/>
          <element name="days" type="int"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
</schema>

=== CrazyForks/jollyday/jollyday-core/src/main/resources/holidays/Holidays_uy.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="uy" description="Uruguay"
               xmlns="http://www.focus_shift.de/jollyday/xml/ns/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.focus_shift.de/jollyday/xml/ns/holiday http://www.focus_shift.de/jollyday/xml/ns/holiday/Holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
    <Fixed month="APRIL" day="19" descriptionPropertiesKey="LANDING_33_EASTERNERS">
      <MovingCondition substitute="TUESDAY" with="PREVIOUS" weekday="MONDAY"/>
      <MovingCondition substitute="WEDNESDAY" with="PREVIOUS" weekday="MONDAY"/>
      <MovingCondition substitute="THURSDAY" with="NEXT" weekday="MONDAY"/>
      <MovingCondition substitute="FRIDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="MAY" day="18" descriptionPropertiesKey="LAS_PIEDRAS">
      <MovingCondition substitute="TUESDAY" with="PREVIOUS" weekday="MONDAY"/>
      <MovingCondition substitute="WEDNESDAY" with="PREVIOUS" weekday="MONDAY"/>
      <MovingCondition substitute="THURSDAY" with="NEXT" weekday="MONDAY"/>
      <MovingCondition substitute="FRIDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <Fixed month="JUNE" day="19" descriptionPropertiesKey="ARTIGAS"/>
    <Fixed month="JULY" day="18" descriptionPropertiesKey="CONSTITUTION_DAY"/>
    <Fixed month="AUGUST" day="25" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="NOVEMBER" day="2" descriptionPropertiesKey="ALL_SOULS"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="OCTOBER" day="12" descriptionPropertiesKey="RACE">
      <MovingCondition substitute="TUESDAY" with="PREVIOUS" weekday="MONDAY"/>
      <MovingCondition substitute="WEDNESDAY" with="PREVIOUS" weekday="MONDAY"/>
      <MovingCondition substitute="THURSDAY" with="NEXT" weekday="MONDAY"/>
      <MovingCondition substitute="FRIDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>
    <ChristianHoliday type="EASTER" descriptionPropertiesKey="christian.EASTER"/>
    <ChristianHoliday type="SHROVE_MONDAY" descriptionPropertiesKey="christian.SHROVE_MONDAY"/>
    <ChristianHoliday type="CARNIVAL" descriptionPropertiesKey="christian.CARNIVAL"/>
    <ChristianHoliday type="MAUNDY_THURSDAY" descriptionPropertiesKey="christian.MAUNDY_THURSDAY"/>
    <ChristianHoliday type="GOOD_FRIDAY" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
  </Holidays>
</Configuration>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_is_2010.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="is" description="Iceland"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="APRIL" day="4"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="DECEMBER" day="26"/>
    <Fixed month="DECEMBER" day="24" descriptionPropertiesKey="CHRISTMAS_EVE"/>
    <Fixed month="JANUARY" day="1"/>
    <Fixed month="JANUARY" day="6"/>
    <Fixed month="MAY" day="13"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="APRIL" day="5"/>
    <Fixed month="DECEMBER" day="1"/>
    <Fixed month="JUNE" day="17"/>
    <Fixed month="JUNE" day="24"/>
    <Fixed month="DECEMBER" day="31"/>
    <Fixed month="FEBRUARY" day="18"/>
    <Fixed month="MARCH" day="1"/>
    <Fixed month="NOVEMBER" day="16"/>
  </Holidays>
</Configuration>

=== CrazyForks/jollyday/jollyday-core/src/main/resources/holidays/Holidays_hu.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="hu" description="Hungary"
               xmlns="http://www.focus_shift.de/jollyday/xml/ns/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.focus_shift.de/jollyday/xml/ns/holiday http://www.focus_shift.de/jollyday/xml/ns/holiday/Holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="MARCH" day="15" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="AUGUST" day="20" descriptionPropertiesKey="STEPHENS"/>
    <Fixed month="OCTOBER" day="23" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    <Fixed month="DECEMBER" day="24" descriptionPropertiesKey="CHRISTMAS_EVE"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="STEPHENS"/>
    <ChristianHoliday type="EASTER" descriptionPropertiesKey="christian.EASTER"/>
    <ChristianHoliday type="GOOD_FRIDAY" descriptionPropertiesKey="christian.GOOD_FRIDAY" validFrom="2017"/>
    <ChristianHoliday type="EASTER_MONDAY" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <ChristianHoliday type="WHIT_MONDAY" descriptionPropertiesKey="christian.WHIT_MONDAY"/>
  </Holidays>
</Configuration>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_gb_2010.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="gb" description="United Kingdom of Great Britain and Northern Ireland"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="APRIL" day="2" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="MAY" day="3" descriptionPropertiesKey="EARLY_MAY_BANK_HOLIDAY"/>
    <Fixed month="MAY" day="31" descriptionPropertiesKey="SPRING_BANK_HOLIDAY"/>
    <Fixed month="DECEMBER" day="27" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="28" descriptionPropertiesKey="BOXING_DAY"/>
  </Holidays>
  <SubConfigurations hierarchy="en" description="England">
    <Holidays>
      <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
      <Fixed month="APRIL" day="5" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
      <Fixed month="AUGUST" day="30" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
    </Holidays>
  </SubConfigurations>
  <SubConfigurations hierarchy="ni" description="Northern Ireland">
    <Holidays>
      <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
      <Fixed month="MARCH" day="17" descriptionPropertiesKey="ST_PATRICK"/>
      <Fixed month="JULY" day="12" descriptionPropertiesKey="BATTLE_BOYNE"/>
      <Fixed month="APRIL" day="5" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
      <Fixed month="AUGUST" day="30" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
    </Holidays>
  </SubConfigurations>
  <SubConfigurations hierarchy="sc" description="Scotland">
    <Holidays>
      <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
      <Fixed month="JANUARY" day="4" descriptionPropertiesKey="NEW_YEAR"/>
      <Fixed month="AUGUST" day="2" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
      <Fixed month="NOVEMBER" day="30" descriptionPropertiesKey="ST_ANDREW"/>
    </Holidays>
  </SubConfigurations>
  <SubConfigurations hierarchy="wa" description="Wales">
    <Holidays>
      <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
      <Fixed month="APRIL" day="5" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
      <Fixed month="AUGUST" day="30" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
    </Holidays>
  </SubConfigurations>
</Configuration>

=== CrazyForks/jollyday/jollyday-core/src/main/resources/holidays/Holidays_gb.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="gb" description="United Kingdom of Great Britain and Northern Ireland"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR">
      <MovingCondition substitute="SATURDAY" with="NEXT" weekday="MONDAY"/>
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
    </Fixed>

    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY">
      <MovingCondition substitute="SATURDAY" with="NEXT" weekday="MONDAY"/>
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="TUESDAY"/>
    </Fixed>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS">
      <MovingCondition substitute="SATURDAY" with="NEXT" weekday="MONDAY"/>
      <MovingCondition substitute="SUNDAY" with="NEXT" weekday="TUESDAY"/>
    </Fixed>

    <!-- The 2020 bank holiday was moved from the 4th to the 8th of May -->
    <Fixed month="MAY" day="8" validFrom="2020" validTo="2020" descriptionPropertiesKey="EARLY_MAY_BANK_HOLIDAY"/>
    <!-- The 2022 spring bank holiday was moved from the 4th of May to the second of June -->
    <Fixed month="JUNE" day="2" validFrom="2022" validTo="2022" descriptionPropertiesKey="SPRING_BANK_HOLIDAY"/>
    <Fixed month="JUNE" day="3" validFrom="2022" validTo="2022" descriptionPropertiesKey="QUEENS_PLATINUM_JUBILEE"/>
    <Fixed month="SEPTEMBER" day="19" validFrom="2022" validTo="2022" descriptionPropertiesKey="QUEENS_STATE_FUNERAL"/>
    <Fixed month="MAY" day="8" validFrom="2023" validTo="2023" descriptionPropertiesKey="KINGS_CORONATION"/>

    <FixedWeekday which="FIRST" weekday="MONDAY" month="MAY" validFrom="1900" validTo="2019" descriptionPropertiesKey="EARLY_MAY_BANK_HOLIDAY"/>
    <FixedWeekday which="SECOND" weekday="FRIDAY" month="MAY" validFrom="2020" validTo="2020" descriptionPropertiesKey="EARLY_MAY_BANK_HOLIDAY"/>
    <FixedWeekday which="FIRST" weekday="MONDAY" month="MAY" validFrom="2021" descriptionPropertiesKey="EARLY_MAY_BANK_HOLIDAY"/>

    <FixedWeekday which="LAST" weekday="MONDAY" month="MAY" validTo="2021" descriptionPropertiesKey="SPRING_BANK_HOLIDAY"/>
    <FixedWeekday which="LAST" weekday="MONDAY" month="MAY" validFrom="2023" descriptionPropertiesKey="SPRING_BANK_HOLIDAY"/>

    <ChristianHoliday type="GOOD_FRIDAY" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
  </Holidays>

  <SubConfigurations hierarchy="eng" description="England">
    <Holidays>
      <FixedWeekday which="LAST" weekday="MONDAY" month="AUGUST" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
      <ChristianHoliday type="EASTER_MONDAY" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    </Holidays>
  </SubConfigurations>
  <!-- England and Wales are always the same -->
  <SubConfigurations hierarchy="wls" description="Wales">
    <Holidays>
      <FixedWeekday which="LAST" weekday="MONDAY" month="AUGUST" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
      <ChristianHoliday type="EASTER_MONDAY" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    </Holidays>
  </SubConfigurations>

  <SubConfigurations hierarchy="sct" description="Scotland">
    <Holidays>
      <Fixed month="JANUARY" day="2" descriptionPropertiesKey="2ND_JANUARY">
        <MovingCondition substitute="SATURDAY" with="NEXT" weekday="MONDAY"/>
        <MovingCondition substitute="SUNDAY" with="NEXT" weekday="TUESDAY"/>
        <MovingCondition substitute="MONDAY" with="NEXT" weekday="TUESDAY"/>
      </Fixed>
      <Fixed month="NOVEMBER" day="30" descriptionPropertiesKey="ST_ANDREW"/>
      <FixedWeekday which="FIRST" weekday="MONDAY" month="AUGUST" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
    </Holidays>
  </SubConfigurations>

  <SubConfigurations hierarchy="nir" description="Northern Ireland">
    <Holidays>
      <Fixed month="MARCH" day="17" descriptionPropertiesKey="ST_PATRICK">
        <MovingCondition substitute="SATURDAY" with="NEXT" weekday="MONDAY"/>
        <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
      </Fixed>
      <Fixed month="JULY" day="12" descriptionPropertiesKey="BATTLE_BOYNE">
        <MovingCondition substitute="SATURDAY" with="NEXT" weekday="MONDAY"/>
        <MovingCondition substitute="SUNDAY" with="NEXT" weekday="MONDAY"/>
      </Fixed>
      <FixedWeekday which="LAST" weekday="MONDAY" month="AUGUST" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
      <ChristianHoliday type="EASTER_MONDAY" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    </Holidays>
  </SubConfigurations>
</Configuration>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_bm_2020.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="bm" description="Bermuda"
               xmlns="http://www.focus_shift.de/jollyday/xml/ns/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.focus_shift.de/jollyday/xml/ns/holiday http://www.focus_shift.de/jollyday/xml/ns/holiday/Holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="APRIL" day="10" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="MAY" day="29" descriptionPropertiesKey="BERMUDA_DAY"/>
    <Fixed month="JUNE" day="15" descriptionPropertiesKey="NATIONAL_HEROES_DAY"/>
    <Fixed month="JULY" day="30" descriptionPropertiesKey="EMANCIPATION_DAY"/>
    <Fixed month="JULY" day="31" descriptionPropertiesKey="MARY_PRINCE_DAY"/>
    <Fixed month="SEPTEMBER" day="7" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="NOVEMBER" day="11" descriptionPropertiesKey="REMEMBRANCE"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="28" descriptionPropertiesKey="BOXING_DAY"/>
  </Holidays>
</Configuration>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_se_2016.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="se" description="Sweden"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
    <Fixed month="MARCH" day="25" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="MARCH" day="27" descriptionPropertiesKey="christian.EASTER"/>
    <Fixed month="MARCH" day="28" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="MAY" day="5" descriptionPropertiesKey="christian.ASCENSION_DAY"/>
    <Fixed month="MAY" day="15" descriptionPropertiesKey="christian.PENTECOST"/>
    <Fixed month="JUNE" day="6" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="JUNE" day="24" descriptionPropertiesKey="MIDSUMMER_EVE"/>
    <Fixed month="JUNE" day="25" descriptionPropertiesKey="MIDSUMMER"/>
    <Fixed month="NOVEMBER" day="5" descriptionPropertiesKey="ALL_SAINTS"/>
    <Fixed month="DECEMBER" day="24" descriptionPropertiesKey="CHRISTMAS_EVE"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY"/>
    <Fixed month="DECEMBER" day="31" descriptionPropertiesKey="NEW_YEARS_EVE"/>
  </Holidays>
</Configuration>

=== CrazyForks/jollyday/jollyday-core/src/main/resources/holidays/Holidays_no.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="no" description="Norway"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="MAY" day="17" descriptionPropertiesKey="CONSTITUTION_DAY"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="STEPHENS"/>
    <ChristianHoliday type="EASTER" descriptionPropertiesKey="christian.EASTER"/>
    <ChristianHoliday type="MAUNDY_THURSDAY" descriptionPropertiesKey="christian.MAUNDY_THURSDAY"/>
    <ChristianHoliday type="GOOD_FRIDAY" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <ChristianHoliday type="EASTER_MONDAY" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <ChristianHoliday type="ASCENSION_DAY" descriptionPropertiesKey="christian.ASCENSION_DAY"/>
    <ChristianHoliday type="WHIT_MONDAY" descriptionPropertiesKey="christian.WHIT_MONDAY"/>
    <ChristianHoliday type="PENTECOST" descriptionPropertiesKey="christian.PENTECOST"/>
  </Holidays>
</Configuration>
