=== CrazyForks/jollyday/jollyday-core/src/main/resources/Holiday.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/Holiday"
        xmlns:tns="http://www.example.org/Holiday"
        elementFormDefault="qualified">

  <simpleType name="Weekday">
    <restriction base="string">
      <enumeration value="MONDAY"/>
      <enumeration value="TUESDAY"/>
      <enumeration value="WEDNESDAY"/>
      <enumeration value="THURSDAY"/>
      <enumeration value="FRIDAY"/>
      <enumeration value="SATURDAY"/>
      <enumeration value="SUNDAY"/>
    </restriction>
  </simpleType>

  <simpleType name="Month">
    <restriction base="string">
      <enumeration value="JANUARY"/>
      <enumeration value="FEBRUARY"/>
      <enumeration value="MARCH"/>
      <enumeration value="APRIL"/>
      <enumeration value="MAY"/>
      <enumeration value="JUNE"/>
      <enumeration value="JULY"/>
      <enumeration value="AUGUST"/>
      <enumeration value="SEPTEMBER"/>
      <enumeration value="OCTOBER"/>
      <enumeration value="NOVEMBER"/>
      <enumeration value="DECEMBER"/>
    </restriction>
  </simpleType>

  <complexType name="RelativeToFixed">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <choice maxOccurs="1" minOccurs="1">
            <element name="Days" type="int" maxOccurs="1" minOccurs="0"/>
            <element name="Weekday" type="tns:Weekday" maxOccurs="1" minOccurs="0"/>
          </choice>
          <element name="When" type="tns:When"/>
          <element name="Date" type="tns:Fixed"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Holidays">
    <sequence>
      <element name="Fixed" type="tns:Fixed" maxOccurs="unbounded" minOccurs="0"/>
      <element name="RelativeToFixed" type="tns:RelativeToFixed" maxOccurs="unbounded" minOccurs="0"/>
      <element name="RelativeToWeekdayInMonth" type="tns:RelativeToWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <element name="FixedWeekday" type="tns:FixedWeekdayInMonth" maxOccurs="unbounded" minOccurs="0"/>
      <element name="ChristianHoliday" type="tns:ChristianHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <element name="IslamicHoliday" type="tns:IslamicHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <element name="FixedWeekdayBetweenFixed" type="tns:FixedWeekdayBetweenFixed" maxOccurs="unbounded" minOccurs="0"/>
      <element name="FixedWeekdayRelativeToFixed" type="tns:FixedWeekdayRelativeToFixed" maxOccurs="unbounded"
               minOccurs="0"/>
      <element name="EthiopianOrthodoxHoliday" type="tns:EthiopianOrthodoxHoliday" maxOccurs="unbounded" minOccurs="0"/>
      <element name="RelativeToEasterSunday" type="tns:RelativeToEasterSunday" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
  </complexType>

  <element name="Configuration" type="tns:Configuration"/>

  <complexType name="Configuration">
    <sequence>
      <element name="Holidays" type="tns:Holidays"/>
      <element name="SubConfigurations" type="tns:Configuration" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="hierarchy" type="string"/>
    <attribute name="description" type="string"/>
  </complexType>

  <complexType name="Fixed">
    <complexContent>
      <extension base="tns:MoveableHoliday">
        <attribute name="month" type="tns:Month"/>
        <attribute name="day">
          <simpleType>
            <restriction base="int">
              <minInclusive value="1"/>
              <maxInclusive value="31"/>
            </restriction>
          </simpleType>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="When">
    <restriction base="string">
      <enumeration value="BEFORE"/>
      <enumeration value="AFTER"/>
      <enumeration value="CLOSEST"/>
    </restriction>
  </simpleType>

  <complexType name="FixedWeekdayInMonth">
    <complexContent>
      <extension base="tns:Holiday">
        <attribute name="which" type="tns:Which"/>
        <attribute name="weekday" type="tns:Weekday"/>
        <attribute name="month" type="tns:Month"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="Which">
    <restriction base="string">
      <enumeration value="FIRST"/>
      <enumeration value="SECOND"/>
      <enumeration value="THIRD"/>
      <enumeration value="FOURTH"/>
      <enumeration value="LAST"/>
    </restriction>
  </simpleType>

  <complexType name="RelativeToWeekdayInMonth">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="FixedWeekday" type="tns:FixedWeekdayInMonth"/>
        </sequence>
        <attribute name="weekday" type="tns:Weekday"/>
        <attribute name="when" type="tns:When"/>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="IslamicHoliday">
    <complexContent>
      <extension base="tns:Holiday">
        <attribute name="type" type="tns:IslamicHolidayType"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="IslamicHolidayType">
    <restriction base="string">
      <enumeration value="NEWYEAR"/>
      <enumeration value="ASCHURA"/>
      <enumeration value="MAWLID_AN_NABI"/>
      <enumeration value="LAILAT_AL_MIRAJ"/>
      <enumeration value="LAILAT_AL_BARAT"/>
      <enumeration value="RAMADAN"/>
      <enumeration value="LAILAT_AL_QADR"/>
      <enumeration value="RAMADAN_END"/>
      <enumeration value="ID_AL_FITR"/>
      <enumeration value="ID_AL_FITR_2"/>
      <enumeration value="ID_AL_FITR_3"/>
      <enumeration value="ARAFAAT"/>
      <enumeration value="ID_UL_ADHA"/>
      <enumeration value="ID_UL_ADHA_2"/>
      <enumeration value="ID_UL_ADHA_3"/>
    </restriction>
  </simpleType>

  <simpleType name="ChronologyType">
    <restriction base="string">
      <enumeration value="JULIAN"/>
      <enumeration value="GREGORIAN"/>
    </restriction>
  </simpleType>

  <complexType name="ChristianHoliday">
    <complexContent>
      <extension base="tns:MoveableHoliday">
        <attribute name="type" type="tns:ChristianHolidayType"/>
        <attribute name="chronology" type="tns:ChronologyType"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="HolidayType">
    <restriction base="string">
      <enumeration value="OFFICIAL_HOLIDAY"/>
      <enumeration value="UNOFFICIAL_HOLIDAY"/>
    </restriction>
  </simpleType>

  <simpleType name="ChristianHolidayType">
    <restriction base="string">
      <enumeration value="GOOD_FRIDAY"/>
      <enumeration value="EASTER_MONDAY"/>
      <enumeration value="ASCENSION_DAY"/>
      <enumeration value="WHIT_MONDAY"/>
      <enumeration value="CORPUS_CHRISTI"/>
      <enumeration value="MAUNDY_THURSDAY"/>
      <enumeration value="ASH_WEDNESDAY"/>
      <enumeration value="MARDI_GRAS"/>
      <enumeration value="GENERAL_PRAYER_DAY"/>
      <enumeration value="CLEAN_MONDAY"/>
      <enumeration value="SHROVE_MONDAY"/>
      <enumeration value="PENTECOST"/>
      <enumeration value="CARNIVAL"/>
      <enumeration value="EASTER_SATURDAY"/>
      <enumeration value="EASTER_TUESDAY"/>
      <enumeration value="SACRED_HEART"/>
      <enumeration value="EASTER"/>
      <enumeration value="PENTECOST_MONDAY"/>
      <enumeration value="WHIT_SUNDAY"/>
    </restriction>
  </simpleType>

  <complexType name="FixedWeekdayBetweenFixed">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="from" type="tns:Fixed"/>
          <element name="to" type="tns:Fixed"/>
        </sequence>
        <attribute name="weekday" type="tns:Weekday"/>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="Holiday" abstract="true">
    <attribute name="validFrom" type="int"/>
    <attribute name="validTo" type="int"/>
    <attribute name="every" type="tns:HolidayCycleType" default="EVERY_YEAR"/>
    <attribute name="descriptionPropertiesKey" type="string"/>
    <attribute name="localizedType" type="tns:HolidayType" default="OFFICIAL_HOLIDAY"/>
  </complexType>

  <simpleType name="Substituted">
    <restriction base="string">
      <enumeration value="ON_SATURDAY"/>
      <enumeration value="ON_SUNDAY"/>
      <enumeration value="ON_WEEKEND"/>
      <enumeration value="ON_TUESDAY"/>
      <enumeration value="ON_WEDNESDAY"/>
    </restriction>
  </simpleType>

  <simpleType name="With">
    <restriction base="string">
      <enumeration value="NEXT"/>
      <enumeration value="PREVIOUS"/>
    </restriction>
  </simpleType>

  <complexType name="MovingCondition">
    <attribute name="substitute" type="tns:Weekday"/>
    <attribute name="with" type="tns:With"/>
    <attribute name="weekday" type="tns:Weekday"/>
  </complexType>

  <complexType name="MoveableHoliday" abstract="true">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="MovingCondition" type="tns:MovingCondition" maxOccurs="unbounded" minOccurs="0"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="EthiopianOrthodoxHoliday">
    <complexContent>
      <extension base="tns:Holiday">
        <attribute name="type" type="tns:EthiopianOrthodoxHolidayType"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="EthiopianOrthodoxHolidayType">
    <restriction base="string">
      <enumeration value="TIMKAT"/>
      <enumeration value="ENKUTATASH"/>
      <enumeration value="MESKEL"/>
    </restriction>
  </simpleType>

  <complexType name="FixedWeekdayRelativeToFixed">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="day" type="tns:Fixed"/>
        </sequence>
        <attribute name="which" type="tns:Which"/>
        <attribute name="weekday" type="tns:Weekday"/>
        <attribute name="when" type="tns:When"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="HolidayCycleType">
    <restriction base="string">
      <enumeration value="EVERY_YEAR"/>
      <enumeration value="TWO_YEARS"/>
      <enumeration value="THREE_YEARS"/>
      <enumeration value="FOUR_YEARS"/>
      <enumeration value="FIVE_YEARS"/>
      <enumeration value="SIX_YEARS"/>
      <enumeration value="ODD_YEARS"/>
      <enumeration value="EVEN_YEARS"/>
    </restriction>
  </simpleType>

  <complexType name="RelativeToEasterSunday">
    <complexContent>
      <extension base="tns:Holiday">
        <sequence>
          <element name="chronology" type="tns:ChronologyType"/>
          <element name="days" type="int"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
</schema>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_gb_2014.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="gb" description="United Kingdom of Great Britain and Northern Ireland"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="APRIL" day="18" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="MAY" day="5" descriptionPropertiesKey="EARLY_MAY_BANK_HOLIDAY"/>
    <Fixed month="MAY" day="26" descriptionPropertiesKey="SPRING_BANK_HOLIDAY"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY"/>
  </Holidays>
  <SubConfigurations hierarchy="eng" description="England">
    <Holidays>
      <Fixed month="APRIL" day="21" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
      <Fixed month="AUGUST" day="25" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
    </Holidays>
  </SubConfigurations>
  <SubConfigurations hierarchy="wls" description="Wales">
    <Holidays>
      <Fixed month="APRIL" day="21" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
      <Fixed month="AUGUST" day="25" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
    </Holidays>
  </SubConfigurations>

  <SubConfigurations hierarchy="sct" description="Scotland">
    <Holidays>
      <Fixed month="JANUARY" day="2" descriptionPropertiesKey="2ND_JANUARY"/>
      <Fixed month="AUGUST" day="4" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
      <Fixed month="DECEMBER" day="1" descriptionPropertiesKey="ST_ANDREW"/>
    </Holidays>
  </SubConfigurations>

  <SubConfigurations hierarchy="nir" description="Northern Ireland">
    <Holidays>
      <Fixed month="MARCH" day="17" descriptionPropertiesKey="ST_PATRICK"/>
      <Fixed month="APRIL" day="21" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
      <Fixed month="JULY" day="14" descriptionPropertiesKey="BATTLE_BOYNE"/>
      <Fixed month="AUGUST" day="25" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
    </Holidays>
  </SubConfigurations>
</Configuration>

=== CrazyForks/jollyday/jollyday-core/src/main/resources/holidays/Holidays_ro.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="ro" description="Romania"
               xmlns="http://www.focus_shift.de/jollyday/xml/ns/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.focus_shift.de/jollyday/xml/ns/holiday http://www.focus_shift.de/jollyday/xml/ns/holiday/Holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="2" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="24" validFrom="2017" descriptionPropertiesKey="UNIFICATION"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="JUNE" day="1" validFrom="2017" descriptionPropertiesKey="CHILDRENS_DAY"/>
    <Fixed month="AUGUST" day="15" descriptionPropertiesKey="NAVY_DAY"/>
    <Fixed month="NOVEMBER" day="30" descriptionPropertiesKey="ST_ANDREW"/>
    <Fixed month="DECEMBER" day="1" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="CHRISTMAS"/>
    <ChristianHoliday type="GOOD_FRIDAY" chronology="JULIAN" validFrom="2018" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <ChristianHoliday type="EASTER" chronology="JULIAN" descriptionPropertiesKey="christian.EASTER"/>
    <ChristianHoliday type="EASTER_MONDAY" chronology="JULIAN" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <ChristianHoliday type="PENTECOST" chronology="JULIAN" descriptionPropertiesKey="christian.PENTECOST"/>
    <ChristianHoliday type="WHIT_MONDAY" chronology="JULIAN" descriptionPropertiesKey="christian.WHIT_MONDAY"/>
  </Holidays>
</Configuration>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_gg_2020.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="gg" description="Guernsey"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="APRIL" day="10" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="APRIL" day="13" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <Fixed month="MAY" day="8" descriptionPropertiesKey="MAY_DAY_BANK_HOLIDAY"/>
    <Fixed month="MAY" day="9" descriptionPropertiesKey="LIBERATION"/>
    <Fixed month="MAY" day="25" descriptionPropertiesKey="SPRING_BANK_HOLIDAY"/>
    <Fixed month="AUGUST" day="31" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="DECEMBER" day="28" descriptionPropertiesKey="BOXING_DAY"/>
  </Holidays>
</Configuration>

=== CrazyForks/jollyday/jollyday-core/src/main/resources/holidays/Holidays_mk.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="mk" description="North Macedonia"
               xmlns="https://focus_shift.de/jollyday/xml/ns/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/xml/ns/holiday https://focus_shift.de/jollyday/xml/ns/holiday/Holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="2" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="JANUARY" day="7" descriptionPropertiesKey="CHRISTMAS"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="MAY" day="24" descriptionPropertiesKey="CYRUS_METHODIUS"/>
    <Fixed month="AUGUST" day="2" descriptionPropertiesKey="REPUBLIC_DAY"/>
    <Fixed month="SEPTEMBER" day="8" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="OCTOBER" day="11" descriptionPropertiesKey="REVOLUTION"/>
    <Fixed month="OCTOBER" day="23" descriptionPropertiesKey="NATIONAL_DAY"/>
    <Fixed month="DECEMBER" day="8" descriptionPropertiesKey="SAINT_CLEMENT"/>
    <ChristianHoliday type="EASTER" chronology="JULIAN" descriptionPropertiesKey="christian.EASTER"/>
    <ChristianHoliday type="GOOD_FRIDAY" chronology="JULIAN" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <ChristianHoliday type="EASTER_MONDAY" chronology="JULIAN" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <IslamicHoliday type="ID_AL_FITR" descriptionPropertiesKey="islamic.ID_AL_FITR"/>
  </Holidays>
</Configuration>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_im_2016.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration hierarchy="im" description="Isle of Man"
               xmlns="https://focus_shift.de/jollyday/schema/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://focus_shift.de/jollyday/schema/holiday https://focus_shift.de/jollyday/schema/holiday/holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="MARCH" day="25" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <Fixed month="MARCH" day="28" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <Fixed month="MAY" day="2" descriptionPropertiesKey="EARLY_MAY_BANK_HOLIDAY"/>
    <Fixed month="MAY" day="30" descriptionPropertiesKey="LATE_MAY_BANK_HOLIDAY"/>
    <Fixed month="JUNE" day="10" descriptionPropertiesKey="TT_BANK_HOLIDAY"/>
    <Fixed month="JULY" day="5" descriptionPropertiesKey="TYNWALD"/>
    <Fixed month="AUGUST" day="29" descriptionPropertiesKey="SUMMER_BANK_HOLIDAY"/>
    <Fixed month="DECEMBER" day="26" descriptionPropertiesKey="BOXING_DAY"/>
    <Fixed month="DECEMBER" day="27" descriptionPropertiesKey="CHRISTMAS"/>
  </Holidays>
</Configuration>

=== CrazyForks/jollyday/jollyday-tests/src/test/resources/holidays/Holidays_test_de_2022.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Configuration hierarchy="de" description="Germany" xmlns:tns="http://www.example.org/Holiday"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.example.org/Holiday /Holiday.xsd">
  <tns:Holidays>
    <tns:Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <tns:Fixed month="APRIL" day="15" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <tns:Fixed month="APRIL" day="18" descriptionPropertiesKey="christian.EASTER_MONDAY"/>
    <tns:Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <tns:Fixed month="MAY" day="26" descriptionPropertiesKey="christian.ASCENSION_DAY"/>
    <tns:Fixed month="JUNE" day="6" descriptionPropertiesKey="christian.WHIT_MONDAY"/>
    <tns:Fixed month="OCTOBER" day="3" descriptionPropertiesKey="UNIFICATION_GERMANY"/>
    <tns:Fixed month="DECEMBER" day="25" descriptionPropertiesKey="FIRST_CHRISTMAS_DAY"/>
    <tns:Fixed month="DECEMBER" day="26" descriptionPropertiesKey="SECOND_CHRISTMAS_DAY"/>
  </tns:Holidays>
  <tns:SubConfigurations hierarchy="be" description="Berlin">
    <tns:Holidays>
      <tns:Fixed month="MARCH" day="8" descriptionPropertiesKey="INTERNATIONAL_WOMAN"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="bb" description="Brandenburg">
    <tns:Holidays>
      <tns:Fixed month="APRIL" day="17" descriptionPropertiesKey="christian.EASTER"/>
      <tns:Fixed month="JUNE" day="5" descriptionPropertiesKey="christian.PENTECOST"/>
      <tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="bw" description="Baden-Württemberg">
    <tns:Holidays>
      <tns:Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
      <tns:Fixed month="JUNE" day="16" descriptionPropertiesKey="christian.CORPUS_CHRISTI"/>
      <tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="by" description="Bayern">
    <tns:Holidays>
      <tns:Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
      <tns:Fixed month="JUNE" day="16" descriptionPropertiesKey="christian.CORPUS_CHRISTI"/>
      <tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    </tns:Holidays>
    <tns:SubConfigurations hierarchy="mu" description="München">
      <tns:Holidays>
        <tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
      </tns:Holidays>
    </tns:SubConfigurations>
    <tns:SubConfigurations hierarchy="ag" description="Augsburg">
      <tns:Holidays>
        <tns:Fixed month="AUGUST" day="8" descriptionPropertiesKey="PEACE"/>
        <tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
      </tns:Holidays>
    </tns:SubConfigurations>
    <tns:SubConfigurations hierarchy="wu" description="Würzburg">
      <tns:Holidays>
        <tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
      </tns:Holidays>
    </tns:SubConfigurations>
    <tns:SubConfigurations hierarchy="re" description="Regensburg">
      <tns:Holidays>
        <tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
      </tns:Holidays>
    </tns:SubConfigurations>
    <tns:SubConfigurations hierarchy="in" description="Ingolstadt">
      <tns:Holidays>
        <tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
      </tns:Holidays>
    </tns:SubConfigurations>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="he" description="Hessen">
    <tns:Holidays>
      <tns:Fixed month="APRIL" day="17" descriptionPropertiesKey="christian.EASTER"/>
      <tns:Fixed month="JUNE" day="16" descriptionPropertiesKey="christian.CORPUS_CHRISTI"/>
      <tns:Fixed month="JUNE" day="5" descriptionPropertiesKey="christian.PENTECOST"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="mv" description="Mecklenburg-Vorpommern">
    <tns:Holidays>
      <tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="nw" description="Nordrhein-Westfalen">
    <tns:Holidays>
      <tns:Fixed month="JUNE" day="16" descriptionPropertiesKey="christian.CORPUS_CHRISTI"/>
      <tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="rp" description="Rheinland-Pfalz">
    <tns:Holidays>
      <tns:Fixed month="JUNE" day="16" descriptionPropertiesKey="christian.CORPUS_CHRISTI"/>
      <tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="sl" description="Saarland">
    <tns:Holidays>
      <tns:Fixed month="AUGUST" day="15" descriptionPropertiesKey="ASSUMPTION_DAY"/>
      <tns:Fixed month="JUNE" day="16" descriptionPropertiesKey="christian.CORPUS_CHRISTI"/>
      <tns:Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="sn" description="Saxony">
    <tns:Holidays>
      <tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
      <tns:Fixed month="NOVEMBER" day="16" descriptionPropertiesKey="REPENTANCE_PRAYER"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="st" description="Saxony-Anhalt">
    <tns:Holidays>
      <tns:Fixed month="JANUARY" day="6" descriptionPropertiesKey="EPIPHANY"/>
      <tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="th" description="Thuringia">
    <tns:Holidays>
      <tns:Fixed month="SEPTEMBER" day="20" descriptionPropertiesKey="CHILDRENS_DAY"/>
      <tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="sh" description="Schleswig-Holstein">
    <tns:Holidays>
      <tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="hh" description="Hamburg">
    <tns:Holidays>
      <tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="hb" description="Bremen">
    <tns:Holidays>
      <tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
    </tns:Holidays>
  </tns:SubConfigurations>
  <tns:SubConfigurations hierarchy="ni" description="Lower-Saxony">
    <tns:Holidays>
      <tns:Fixed month="OCTOBER" day="31" descriptionPropertiesKey="REFORMATION_DAY"/>
    </tns:Holidays>
  </tns:SubConfigurations>
</tns:Configuration>

=== CrazyForks/jollyday/jollyday-core/src/main/resources/holidays/Holidays_bo.xml
<?xml version="1.0" encoding="UTF-8"?>

<Configuration hierarchy="bo" description="Bolivia"
               xmlns="http://www.focus_shift.de/jollyday/xml/ns/holiday"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.focus_shift.de/jollyday/xml/ns/holiday http://www.focus_shift.de/jollyday/xml/ns/holiday/Holiday.xsd">
  <Holidays>
    <Fixed month="JANUARY" day="1" descriptionPropertiesKey="NEW_YEAR"/>
    <Fixed month="FEBRUARY" day="2" descriptionPropertiesKey="CANDELARIA"/>
    <Fixed month="MAY" day="1" descriptionPropertiesKey="LABOUR_DAY"/>
    <Fixed month="AUGUST" day="6" descriptionPropertiesKey="INDEPENDENCE_DAY"/>
    <Fixed month="NOVEMBER" day="1" descriptionPropertiesKey="ALL_SAINTS"/>
    <Fixed month="DECEMBER" day="25" descriptionPropertiesKey="CHRISTMAS"/>
    <ChristianHoliday type="EASTER" descriptionPropertiesKey="christian.EASTER"/>
    <ChristianHoliday type="GOOD_FRIDAY" descriptionPropertiesKey="christian.GOOD_FRIDAY"/>
    <ChristianHoliday type="CORPUS_CHRISTI" descriptionPropertiesKey="christian.CORPUS_CHRISTI"/>
  </Holidays>
</Configuration>
